return {
	"nvim-treesitter/nvim-treesitter",
	lazy = true,
	build = ":TSUpdate",
	-- event = { "BufReadPre", "BufNewFile" },
	depends = { "nvim-treesitter/nvim-treesitter-textobjects" },
	ensure_installed = {
		"python",
		"go",
		"zig",
		"rust",
		"c",
		"json",
		"javascript",
		"typescript",
		"tsx",
		"yaml",
		"html",
		"css",
		"prisma",
		"markdown",
		"markdown_inline",
		"svelte",
		"graphql",
		"bash",
		"lua",
		"vim",
		"dockerfile",
		"gitignore",
		"query",
		"vimdoc",
		"c",
	},
	config = function()
		require("nvim-treesitter").setup({})
	end,
}
